version: "3.9"
services:
  tp2intervals:
    image: ghcr.io/costa-alex/tp2intervals:latest
    container_name: tp2intervals
    restart: unless-stopped
    environment:
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Europe/Lisbon"
      SCHEDULER_INTERVAL_HOURS: "${SCHEDULER_INTERVAL_HOURS:-1}"
    ports:
      - "8098:8080"
    volumes:
      - ./data:/data
