app:
  scheduler:
    interval-hours: ${SCHEDULER_INTERVAL_HOURS:1}
  sync-history:
    retention-limit: ${SYNC_HISTORY_RETENTION_LIMIT:100}
  training-peaks:
    api-url: https://tpapi.trainingpeaks.com
  intervals:
    api-url: https://intervals.icu
  trainer-road:
    api-url: https://www.trainerroad.com
  attachments:
    enabled: false

spring:
  application:
    name: workout-relay
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: basic
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlite:/data/workout-relay.sqlite}
    driver-class-name: org.sqlite.JDBC
  jpa:
    open-in-view: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  cache:
    jcache:
      config: classpath:ehcache.xml

server:
  error:
    include-message: never

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    loggers:
      enabled: false

logging:
  file:
    name: ${LOGGING_FILE_NAME:/data/workout-relay.log}
